--DBCC CHECKIDENT ('dbo.ApplicationTypes', RESEED, -1);  
--GO
--delete ApplicationTypes


insert into EntityStatus (Name)
values('')
,('Closed')
,('In Progress')
,('In Progress - Confirmed')
,('In Progress - Tentative')
,('Pipeline')
,('S&I')
,('SOM')
,('Turnaround')


insert into Departments (Name)
values ('')
 ,('Mfg DV')

insert into Countries (Name)
values ('')
,('Argentina')
,('Austria')
,('Canada')
,('Denmark')
,('Germany')
,('Global')
,('Hong Kong')
,('India')
,('Indonesia')
,('Luxembourg')
,('Malaysia')
,('Netherlands')
,('Oman')
,('Pakistan')
,('Philippines')
,('Singapore')
,('South Africa')
,('Spain')
,('Thailand')
,('Turkey')
,('UAE (United Arab Emirates)')
,('USA (United States)')


insert into ApplicationTypes (Name)
values ('')
 ,('Application & Infra')
,('Pure Application')


insert into SiteItmFeedbacks(Name)
values ('')
 ,('Amber')
,('Green')
,('Red')	

insert into Sites(Name)
values ('')
,('Buenos Aires (BAR)')
,('Convent (CVR)')
,('Deer Park (DPC)')
,('Deer Park (DPR)')
,('Fredericia (FRE)')
,('Geismar')
,('Geismar (GCC)')
,('Global Sites')
,('Martinez')
,('Martinez (MZR)')
,('Mobile')
,('Mobile (MBC)')
,('Moerdijk')
,('Moerdijk (MOC)')
,('Motiva')
,('Norco')
,('Norco (NCR)')
,('Norco (NOC)')
,('Pernis')
,('Port Dickson (PDI)')
,('Puget Sound (PSR)')
,('Pulau Bukom (PBU)')
,('Qatar')
,('Rheinland')
,('Rheinland (RLR)')
,('Rheinland (RLR) 8PUs')
,('Sarnia (SAC)')
,('Scotford (SCT)')
,('Scotford Upgrader (SCU)')
,('Seraya Jurong Island (SJI)')
,('STCB - Bangalore')
,('STCH-Houston')
,('T&S - Descoped')
,('T&S Germany Terminals')
,('T&S Germany Wave 1')
,('T&S Germany Wave 2')
,('T&S Wave 2')
,('T&S Wave 3')
,('T&S Wave 4')
,('Tabangao (TAB)')
,('TBD')

insert into SubPortfolios(Name)
values('')
,('Business Excellence')
,('Capital Projects')
,('CTM/HMB')
,('Functions')
,('Functions - Other')
,('HSSE')
,('Innovation')
,('REMPTA')
,('S&I')
,('T&PE')
,('Tech. & Production Excellence')


--insert into Projects
--values(1, '100','IntelaTrac 5.1.1 Upgrade', 'Just another description', 'Spoorthi M','CMS',
--1,GETDATE(), 'Ranjith', GETDATE(), 'Ranjith');